# Generated by Django 2.0.1 on 2018-01-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default='UNDEFINED', max_length=300)),
                ('title', models.CharField(blank=True, default='UNDEFINED', max_length=300)),
                ('author', models.CharField(blank=True, default='UNDEFINED', max_length=100)),
                ('brief', models.TextField()),
                ('body', models.TextField()),
                ('source', models.CharField(choices=[('spacedotcom', 'Space.com'), ('spacenews', 'SpaceNews.com')], default='UNDEFINED', max_length=100)),
                ('company', models.ForeignKey(default='UNDEFINED', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='news_articles', to='db_api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tag',
            field=models.ManyToManyField(related_name='news_articles', to='db_api.Tag'),
        ),
    ]
