# Generated by Django 2.0.1 on 2018-01-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0002_auto_20180122_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='company',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='tag',
        ),
    ]
